name: formatting-types
version: '0.1.0.0'
category: Web
author: Kris Jenkins
maintainer: krisajenkins@gmail.com
copyright: 2017 Kris Jenkins
license: BSD3
github: krisajenkins/formatting-types
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
  - text
tests:
  formatting-types-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - formatting-types
